---
abstract: 'For interacting with data in LabKey Server'
author:
  - 'LabKey Software C<info@labkey.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: LabKey-Query
provides:
  LabKey::Query:
    file: lib/LabKey/Query.pm
    version: 1.04
requires:
  Carp: 0
  Data::Dumper: 0
  File::HomeDir: 0
  File::Spec: 0
  FileHandle: 0
  HTTP::Request: 0
  JSON: 2
  LWP::UserAgent: 0
  URI: 0
version: 1.04
